from __future__ import annotations

from pathlib import Path

import pandas as pd


def _tex_escape(text: str) -> str:
    return str(text).replace("_", r"\_")


def write_latex_table(path: Path, df: pd.DataFrame, caption: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if df.empty:
        raise RuntimeError(f"Refusing to write empty LaTeX table: {path}")
    lines = ["% Auto-generated by CB-SAE pipeline", r"\begin{tabular}{" + "l" * len(df.columns) + "}", r"\toprule"]
    lines.append(" & ".join(_tex_escape(c) for c in df.columns) + r" \\")
    lines.append(r"\midrule")
    for _, row in df.iterrows():
        lines.append(" & ".join(_tex_escape(f"{v:.4g}" if isinstance(v, float) else str(v)) for v in row.tolist()) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", f"% {caption}"]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def export_tables(metrics: pd.DataFrame, significance: pd.DataFrame, dataset_summary: pd.DataFrame, config_summary: pd.DataFrame, out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    metrics.to_csv(out_dir / "main_results.csv", index=False)
    significance.to_csv(out_dir / "significance.csv", index=False)
    dataset_summary.to_csv(out_dir / "dataset_summary.csv", index=False)
    config_summary.to_csv(out_dir / "config_summary.csv", index=False)
    write_latex_table(out_dir / "table_main_results.tex", metrics, "Main results")
    write_latex_table(out_dir / "table_significance.tex", significance, "Significance")
    write_latex_table(out_dir / "table_dataset_summary.tex", dataset_summary, "Dataset summary")
    write_latex_table(out_dir / "table_config_summary.tex", config_summary, "Config summary")
